export {default as Dday} from './Dday'
export {default as Credit} from './Credit'
export {default as Keywords} from './Keywords'
export {default as MostCompetition} from './MostCompetition'
export {default as Slider} from './Slider'
export {default as MainPopup} from './MainPopup'